'''
Problem Statement :
Consider all integer combinations of a,b 2<=a<=5, 2<=b<=5
If they are then placed in numerical order, with any repeats removed, we get the following sequence of 15 distinct terms:

4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125

How many distinct terms are in the sequence generated by a,b for 2<=a<=100, 2<=b<=100
'''

def distinctPowers(range_a,range_b):
    uniq_set = set()
    for a in range(2,range_a+1):
        for b in range(2,range_b+1):
            uniq_set.add(a**b)
    
    print("Distinct Powers")
    print("Range for a : {}, b: {}, Size of distinct power set :: {}".format(a,b,len(uniq_set)))
    print(sorted(uniq_set))


distinctPowers(5,5)
distinctPowers(100,100)

